name: HelloWorld                  # ワークフロー名
run-name: by @${{ github.actor }} # ワークフロー実行名
on: push                          # イベント
jobs:                             # ジョブの定義
  hello:                          # ジョブID
    runs-on: ubuntu-latest        # 実行環境
    steps:                        # ステップの定義
      - run: echo "Hello World"   # シェルコマンドの実行
