name: Variables and Secrets
on: push
jobs:
  output:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSW0RD }}
      VARIABLE: ${{ vars.VAR_01 }}
    steps:
      - name: Output secrets
        run: echo "${PASSWORD}"
      - name: Output variables
        run: echo "${VARIABLE}"
