name: GITHUB_OUTPUT and GITHUB_ENV
on: push
jobs:
  var_share:
  steps:
    - id: share
      run: echo "SHARE_VAR=hogehoge" >> "${GITHUB_OUTPUT}"
    - name: id share output
      env: RESULT=${{ steps.share.outputs.SHARE_VAR }}
      run: echo "${RESULT}"
    - name: set
      run: echo "SHARE_VAR=hogehogehogehoge" >> "${GITHUB_ENV}"
    - name: no id output
      env: RESULT=${{ steps.outputs.SHARE_VAR }}
      run: echo "${RESULT}"
